apiVersion: v1
data:
  CURRENCY_EXCHANGE_SERVICE_HOST: {{ .Values.otherServices.currencyConversion.url | quote}}
  CURRENCY_EXCHANGE_SERVICE_PORT: {{ .Values.otherServices.currencyConversion.port | quote}}
kind: ConfigMap
metadata:
  name: currency-conversion-config-map
  namespace: default
